export const PROJECT_ACTIONS = {
    CREATE_PROJECT: 'CREATE_PROJECT',
    CREATE_PROJECT_FAILED: 'CREATE_PROJECT_FAILED',
    CREATE_PROJECT_SUCCESSFUL: 'CREATE_PROJECT_SUCCESSFUL',
    GET_PROJECT: 'GET_PROJECT',
    GET_PROJECT_SUCCESSFUL: 'GET_PROJECT_SUCCESSFUL',
    GET_PROJECT_FAILED: 'GET_PROJECT_FAILED',
};