export const SPRINT_ACTIONS = {
    CREATE_SPRINT: 'CREATE_SPRINT',
    CREATE_SPRINT_FAILED: 'CREATE_SPRINT_FAILED',
    CREATE_SPRINT_SUCCESSFUL: 'CREATE_SPRINT_SUCCESSFUL',
    START_SPRINT: 'START_SPRINT',
    START_SPRINT_FAILED: 'START_SPRINT_FAILED',
    START_SPRINT_SUCCESSFUL: 'START_SPRINT_SUCCESSFUL',
};