export const USER_STORY_ACTIONS = {
    CREATE_USER_STORY: 'CREATE_USER_STORY',
    CREATE_USER_STORY_FAILED: 'CREATE_USER_STORY_FAILED',
    CREATE_USER_STORY_SUCCESSFUL: 'CREATE_USER_STORY_SUCCESSFUL',
    UPDATE_USER_STORY: 'UPDATE_USER_STORY',
    UPDATE_USER_STORY_SUCCESSFUL: 'UPDATE_USER_STORY_SUCCESSFUL',
    UPDATE_USER_STORY_FAILED: 'UPDATE_USER_STORY_FAILED',
};