export const USER_ACTIONS = {
    REGISTER_USER: 'REGISTER_USER',
    REGISTER_USER_FAILED: 'REGISTER_USER_FAILED',
    REGISTER_USER_SUCCESSFUL: 'REGISTER_USER_SUCCESSFUL',
    LOG_IN: 'LOG_IN',
    LOG_IN_SUCCESSFUL: 'LOG_IN_SUCCESSFUL',
    LOG_IN_FAILED: 'LOG_IN_FAILED',
    LOG_OUT: 'LOG_OUT',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILED: 'FETCH_USERS_FAILED'
};