export const USER_ACTIONS = {
    REGISTER_USER: 'REGISTER_USER',
    REGISTER_USER_FAILED: 'REGISTER_USER_FAILED',
    REGISTER_USER_SUCCESSFUL: 'REGISTER_USER_SUCCESSFUL',
    LOG_IN_USER: 'LOG_IN_USER',
    LOG_IN_SUCCESSFUL: 'LOG_IN_SUCCESSFUL',
    LOG_IN_FAILED: 'LOG_IN_FAILED',
    LOG_OUT: 'LOG_OUT'
};